// Generated by FSOps at install/update/repair time - PanelPackageInstaller.cs rewrites ONLY this
// file with the port FSOps is currently configured to run on (FSOPS_PORT, default 5977 - see
// Program.cs). Nothing else in this package changes when the port changes, so repairing or
// reinstalling after moving FSOps to a different port never needs the MSFS SDK or a recompiled
// panel component - see ../../../../README.md "Why the port lives in its own file".
//
// This is the checked-in fallback value (FSOps' documented default port) for anyone who copies
// this package by hand instead of through the app's installer.
window.FSOPS_PANEL_PORT = 5977;
