// <auto-generated />
using System;
using FSOps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSOps.Data.Migrations
{
    [DbContext(typeof(FsOpsDbContext))]
    [Migration("20260814100936_DropPilotStatus")]
    partial class DropPilotStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FSOps.Core.Entities.AircraftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CruiseTasKts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelBurnKgPerHour")
                        .HasColumnType("REAL");

                    b.Property<string>("IcaoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinRunwayFt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyLeaseRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<double>("MtowTonnes")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RangeNm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceCeilingFt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IcaoType");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Airline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Playstyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReputationScore")
                        .HasColumnType("REAL");

                    b.Property<string>("StrategyProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Airport", b =>
                {
                    b.Property<string>("Icao")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElevationFt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasScheduledService")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iata")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<int>("LongestRunwayFt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Icao");

                    b.HasIndex("Iata");

                    b.HasIndex("Icao");

                    b.HasIndex("Name");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FSOps.Core.Entities.EconomyState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AwaySummaryLastViewedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelPricePerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastProcessedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastScheduleResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorldSeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EconomyStates");
                });

            modelBuilder.Entity("FSOps.Core.Entities.FleetAircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AircraftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<double>("AirframeHours")
                        .HasColumnType("REAL");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConditionPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelOnBoardKg")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("GroundedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursSinceACheck")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursSinceCCheck")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReservedForPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("FleetAircraft");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CentrelineDeviationM")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FleetAircraftId")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelPlannedKg")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelUsedKg")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("InUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LandingFpmFirst")
                        .HasColumnType("REAL");

                    b.Property<double?>("LandingFpmHardest")
                        .HasColumnType("REAL");

                    b.Property<double?>("LandingGForce")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxSimulationRateObserved")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("OffUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OutUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaxBooked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaxFlown")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedBlockMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PlannedDepartureUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PositionJumpDetected")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RevenuePosted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SimRateElevated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SlewDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleFlown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("TypeMismatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnflyableReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatsimCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatsimControllersWorked")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("VatsimOnline")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VatsimOnlineFraction")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FSOps.Core.Entities.FlightEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Utc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightEvents");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FleetAircraftId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("FSOps.Core.Entities.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FlightId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Utc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("LedgerTransactions");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<double>("AnnualInterestRate")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaidOff")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("FSOps.Core.Entities.MaintenanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FleetAircraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FleetAircraftId");

                    b.ToTable("MaintenanceEvents");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursFlown")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastFlewUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SkillRating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("FSOps.Core.Entities.PilotSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoSuspendOnMaintenance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("PilotId")
                        .IsUnique();

                    b.ToTable("PilotSchedules");
                });

            modelBuilder.Entity("FSOps.Core.Entities.PilotScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FleetAircraftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PilotScheduleId");

                    b.ToTable("PilotScheduleEntries");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseFare")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirlineId", "FlightNumber");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Runway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Designator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HeadingTrue")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLighted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LatitudeEnd")
                        .HasColumnType("REAL");

                    b.Property<double?>("LatitudeStart")
                        .HasColumnType("REAL");

                    b.Property<int>("LengthFt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LongitudeEnd")
                        .HasColumnType("REAL");

                    b.Property<double?>("LongitudeStart")
                        .HasColumnType("REAL");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WidthFt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportIcao");

                    b.ToTable("Runways");
                });

            modelBuilder.Entity("FSOps.Core.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltitudeUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistanceUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimBriefPilotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Use24HourClock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VatsimCid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("FSOps.Core.Entities.Runway", b =>
                {
                    b.HasOne("FSOps.Core.Entities.Airport", null)
                        .WithMany("Runways")
                        .HasForeignKey("AirportIcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSOps.Core.Entities.Airport", b =>
                {
                    b.Navigation("Runways");
                });
#pragma warning restore 612, 618
        }
    }
}
